### Basic Numpy Functions


In [16]:
import numpy as np

In [17]:
type(([[123,12,123,12,33], [],[]]))
n = np.arange(27)
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
m = np.asarray([[123,12,123,12,33], [],[]])
type(m)


numpy.ndarray

#### Create Numpy Arrays from Images/ Vice-versa

In [19]:
import cv2

# noinspection PyUnresolvedReferences
img = cv2.imread('resources/small_gray_pixels.png', 0)
img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       ...,
       [255, 195, 195, ..., 218, 255, 255],
       [255, 195, 195, ..., 218, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [20]:
# noinspection PyUnresolvedReferences
color_img = cv2.imread('resources/color_pixels.png', 2)
# noinspection PyUnresolvedReferences
cv2.imwrite('resources/new_color_image.png', color_img)

True

In [21]:
a=[1, 2, 3]
img[0:2]


array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255

In [22]:
img[2,4]

157

In [27]:
for i in img.T:
    pass # print(i)

In [28]:
for i in color_img.flat:
    pass # print(i)

### Stacking and Slicing 

In [31]:
imgs = np.hstack((img, img))
imgs

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       ...,
       [255, 195, 195, ..., 218, 255, 255],
       [255, 195, 195, ..., 218, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [32]:
print(imgs)

[[255 255 255 ... 255 255 255]
 [255 157 157 ... 156 255 255]
 [255 157 157 ... 156 255 255]
 ...
 [255 195 195 ... 218 255 255]
 [255 195 195 ... 218 255 255]
 [255 255 255 ... 255 255 255]]


In [40]:
lst = np.hsplit(imgs, 1)
lst

[array([[255, 255, 255, ..., 255, 255, 255],
        [255, 157, 157, ..., 156, 255, 255],
        [255, 157, 157, ..., 156, 255, 255],
        ...,
        [255, 195, 195, ..., 218, 255, 255],
        [255, 195, 195, ..., 218, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)]

In [41]:
lst[0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       [255, 157, 157, ..., 156, 255, 255],
       ...,
       [255, 195, 195, ..., 218, 255, 255],
       [255, 195, 195, ..., 218, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)